name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/task_container:${{ github.ref_name }} .
        docker save ${{ secrets.DOCKER_USERNAME }}/task_container:${{ github.ref_name }} -o image.tar
    - name: Upload image to workspace
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: image.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download image from workspace
      uses: actions/download-artifact@v2
      with:
        name: docker-image
        path: image.tar

    - name: Load Docker image
      run: docker load -i image.tar

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/task_container:${{ github.ref_name }}
